<G> ::= <P>+ ;
<P> ::= NT #1 "::=" <PLIST> ";" #9 ;
<PLIST> ::= #5 <RHS> ( "|" #5 <RHS> )* ;
<RHS> ::= <ITEM>+ | EPSILON ;
<ITEM> ::= ( <S> | "(" #2 <PLIST> ")" #3 ) <CARD>? #4;
<CARD> ::= "*" | "+" | "?" ;
<S> ::= T #6 | NT #7 | SA #8 ;